export const products = [
  {
    id: 1,
    title: "Musle Gain",
    description: "",
    price: "500",
    img:"supli1.jpg",
    quantity:0
  },
  {
    id: 2,
    title: "Weight Loss",
    description: "white in color",
    price: "230",
    img: "supli2.jpg",
    quantity: 0,
  },
  {
    id: 3,
    title: "Redmi 9",
    description: "black in color",
    price: "3500",
    img: "supli3.jpg",
    quantity: 0,
  },
  {
    id: 4,
    title: "Iphone 12",
    description: "Best mobile ever",
    price: "90500",
    img: "supli4.jpg",
    quantity: 0,
  },
  {
    id: 5,
    title: "Samsung S21",
    description: "black in color",
    price: "2500",
    img: "supli4.jpg",
    quantity: 0,
  },
  {
    id: 6,
    title: "Redmi 9",
    description: "black in color",
    price: "3500",
    img: "supli4.jpg",
    quantity: 0,
  },
  {
    id: 7,
    title: "Samsung S21",
    description: "black in color",
    price: "2500",
    img: "supli4.jpg",
    quantity: 0,
  },
  {
    id: 8,
    title: "Iphone 12",
    description: "Best mobile ever",
    price: "900",
    img: "supli4.jpg",
    quantity: 0,
  },
  {
    id: 9,
    title: "Samsung S21",
    description: "black in color",
    price: "2500",
    img: "supli4.jpg",
    quantity: 0,
  },
];
